---
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--filter-files"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-toml

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: fix-byte-order-marker
      - id: debug-statements

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - darglint
          - flake8-2020 >= 1.6.0
          - flake8-docstrings # uses pydocstyle
          - flake8-isort >= 4.1.1

  - repo: https://github.com/asottile/pyupgrade
    # keep it after flake8
    rev: v3.15.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - pygithub
          - pytest
          - types-requests

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        additional_dependencies:
          - PyYAML
          - pygithub
          - pytest
          - semver

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest .github scripts -vvvv
        types: [python]
        language: python
        pass_filenames: false
        always_run: true
        additional_dependencies:
          - pytest
          - pygithub
          - pyyaml
