name: Retrieve collection information
description: Extract collection infromation from the galaxy.yml file

inputs:
  path:
    description: "Path to the galaxy.yml file"
    required: true
  version:
    description: "Version of the collection"
    required: true
outputs:
  tar_file:
    description: The collection tarball when built
    value: ${{ steps.namespace.outputs.value }}-${{ steps.name.outputs.value }}-${{ inputs.version }}.tar.gz
  collection_path:
    description: The final collection path
    value: /home/runner/collections/ansible_collections/${{ steps.namespace.outputs.value }}/${{ steps.name.outputs.value }}
  dependency:
    description: The collection dependency
    value: ${{ steps.dependency.outputs.value }}

runs:
  using: composite
  steps:
    - name: Github action python requirements
      run: pip3 install yq
      shell: bash

    - name: Set the version number in galaxy.yml
      run: |
        yq -yi '.version="${{ inputs.version }}"' '${{ inputs.path }}'
      shell: bash

    - name: Extract collection namespace
      id: namespace
      run: |
        echo "::set-output name=value::$(yq -r '.namespace' '${{ inputs.path }}')"
      shell: bash

    - name: Extract collection name
      id: name
      run: |
        echo "::set-output name=value::$(yq -r '.name' '${{ inputs.path }}')"
      shell: bash

    - name: Extract version
      id: version
      run: |
        echo "::set-output name=value::$(yq -r '.version' '${{ inputs.path }}')"
      shell: bash

    - name: Extract dependency
      id: dependency
      run: |
        echo "::set-output name=value::$(yq -r '.dependencies | keys | join(" ")' '${{ inputs.path }}')"
      shell: bash

    - name: Github action python requirements
      run: pip3 uninstall yq -y
      shell: bash
